version: "3"

env:
  CLIENT_FOLDER: /home/naa/.minecraft
  COMPOSE_F: docker-compose.yml

tasks:
  server:debug:rerun:
    cmds:
      - sudo rm -R data | true
      - mkdir data
      - cp -r configs data
      - echo $COMPOSE_F
      - docker-compose -f $COMPOSE_F down ;  docker-compose -f $COMPOSE_F build ; docker-compose -f $COMPOSE_F run --rm --service-ports app

  server:debug:run:
    cmds:
      - docker-compose -f $COMPOSE_F down ; docker-compose -f $COMPOSE_F build && docker-compose -f $COMPOSE_F run --rm --service-ports app

  client:mount:
    cmds:
      - sudo mount $(pwd)/mods $CLIENT_FOLDER/mods

  server:build:
    cmds:
      - DOCKER_HOST=ssh://minecraft docker-compose build
